# Bonus Exercise_1

In [2]:
import pandas as pd
import numpy as np

In [ ]:
# import data
dir = '../data/processed/'
filename = 'demo_100.csv'
df_demo = pd.read_csv(dir + filename)

In [32]:
# keep only the model_type with bridge
df_demo_bridge = df_demo.copy()
df_demo_bridge = df_demo_bridge[df_demo_bridge['model_type'] == 'bridge']

# keep only the road with N1
df_demo_bridge = df_demo_bridge[df_demo_bridge['road'] == 'N1']

In [33]:
df_demo_bridge.head()

,road,id,model_type,name,lat,lon,length,condition,road_lrp
2,N1,N1_2,bridge,.,23.698739,90.458861,0.800,A,N1LRP001a
6,N1,N1_6,bridge,.,23.694664,90.487775,0.925,A,N1LRP004b
12,N1,N1_12,bridge,Kanch pur Bridge.,23.705060,90.523214,0.473,A,N1LRP008b
15,N1,N1_15,bridge,KATCHPUR BOX CULVERT,23.696400,90.535099,0.040,B,N1LRP010a
16,N1,N1_16,bridge,NOYAPARA CULVERT,23.694391,90.537574,0.337,A,N1LRP010b

In [34]:
df_demo_bridge.sort_values(by='length', ascending=False).head()

,road,id,model_type,name,lat,lon,length,condition,road_lrp
262,N1,N1_262,bridge,DEBIPUR SLAB CULVERT,23.026980,91.365500,1.021,A,N1LRP143a
298,N1,N1_298,bridge,BAROYARHAT BOX CULVERT,22.891639,91.535472,1.000,A,N1LRP169a
301,N1,N1_301,bridge,UTTOR SONAPAR BOX CULVERT,22.874699,91.540884,0.970,A,N1LRP171a
641,N1,N1_641,bridge,BANIYAR CHORA,21.803424,92.077232,0.968,A,N1LRP323b
443,N1,N1_443,bridge,CORNAIL HAT BOX CULVERT,22.369684,91.773926,0.960,A,N1LRP234a

In [37]:
# Define scoring system
condition_priority = {'A': 1, 'B': 2, 'C': 3, 'D': 4}  # Higher = worse condition

# Normalize bridge length (scale 1-4 based on max length)
df_demo_bridge['normalized_length'] = (df_demo_bridge['length'] / df_demo_bridge['length'].max()) * 4

# Assign condition scores
df_demo_bridge['condition_score'] = df_demo_bridge['condition'].map(condition_priority)

# Define weights (adjust as needed)
W1 = 0.7  # Weight for condition
W2 = 0.3  # Weight for length

# Compute final prioritization score
df_demo_bridge['priority_score'] = (
    W1 * df_demo_bridge['condition_score'] +
    W2 * df_demo_bridge['normalized_length'] 
)

# Rank bridges based on priority score
df_demo_bridge = df_demo_bridge.sort_values(by='priority_score', ascending=False).reset_index(drop=True)

# Select top 5 bridges
top_5_bridges = df_demo_bridge.head(5)
top_5_bridges

,road,id,model_type,name,lat,lon,length,condition,road_lrp,normalized_length,condition_score,priority_score
0,N1,N1_842,bridge,MORICHIA,21.321109,92.088884,0.447,D,N1LRP394a,1.751224,4,3.325367
1,N1,N1_850,bridge,SHAPUR STEEL BEAM AND RCC SLAB,21.299745,92.097477,0.433,D,N1LRP396b,1.696376,4,3.308913
2,N1,N1_278,bridge,Lemua Bridge(L),22.961449,91.442996,0.951,C,N1LRP155a,3.725759,3,3.217728
3,N1,N1_92,bridge,SARKAR BARI CULVERT,23.530766,90.780080,0.895,C,N1LRP046a,3.506366,3,3.151910
4,N1,N1_788,bridge,SHAMMOTI PARA,21.406361,92.058047,0.290,D,N1LRP382c,1.136141,4,3.140842